### ISSUE TITLE
Salesforce Sandbox mode and TLS 1.0 on both python 2.x and 3.x

### ISSUE THREAD

**Issue by aaj5956** [simple-salesforce/simple-salesforce#125]
$ python simple_sfdc.py
Traceback (most recent call last):
  File "simple_sfdc.py", line 9, in <module>
    sf = Salesforce(username='xxxx', password='xxxx', security_token='xxxx', sandbox = True)
  File "/Library/Python/2.7/site-packages/simple_salesforce/api.py", line 92, in **init**
    proxies=self.proxies)
  File "/Library/Python/2.7/site-packages/simple_salesforce/login.py", line 135, in SalesforceLogin
    raise SalesforceAuthenticationFailed(except_code, except_msg)
simple_salesforce.login.SalesforceAuthenticationFailed: UNSUPPORTED_CLIENT: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.

Facing the above issue for salesforce sandbox mode. Using the latest 0.69 version of simple_salesforce. 
P.S. The production version is working fine.

**Comment by LarryKlugerDS** [comment]
Same issue here. Is the version via pip the same as the repo's version?

Thanks,
Larry

**Comment by aaj5956** [comment]
I solved this issue with updating the pyopenssl module.
Try sudo pip install --upgrade pyopenssl
I guess python uses its own ssl. You need to upgrade the version.

**Comment by LarryKlugerDS** [comment]
Thank you @aaj5956 -- After upgrading both pyOpenSSL and requests to the versions below, everything worked fine.
 
* pyOpenSSL==16.1.0
* requests==2.11.1

This issue can be closed.

**Comment by demianbrecht** [comment]
This should have been fixed with the 0.68 release with the change to depending on the requests secure package. Please let me know if that's not the case for some reason.

**Comment by LarryKlugerDS** [comment]
Hi @demianbrecht 

Thank you for your great software. Yes, after the support libraries pyOpenSSL and requests were updated to the versions listed above, everything worked great with TLS 1.1.

Regards,
Larry

**Comment by petershvets** [comment]
I updated both:
>>> pkg_resources.get_distribution("requests").version
'2.11.1'
>>> pkg_resources.get_distribution("pyOpenSSL").version
'16.1.0'

Running Python 3.5.1, upgraded to simple-salesforce 0.70
However, I am still not able to connect:

INFO: Connecting to SFDC
/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
Traceback (most recent call last):
  File "schema_validator.py", line 114, in <module>
    main()
  File "schema_validator.py", line 108, in main
    sf = Salesforce(username='myuser', password='mypasswd', security_token='mytoken')
  File "/usr/local/lib/python3.5/site-packages/simple_salesforce-0.70-py3.5.egg/simple_salesforce/api.py", line 117, in __init__
  File "/usr/local/lib/python3.5/site-packages/simple_salesforce-0.70-py3.5.egg/simple_salesforce/login.py", line 156, in SalesforceLogin
simple_salesforce.login.SalesforceAuthenticationFailed: UNSUPPORTED_CLIENT: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.
